server:
  port: 8810
  inner:
    port: 8811
  context-path: /
spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://118.31.47.102:3306/vote?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 1
    maxWait: 100
    minIdle: 100
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20 
    

logging:
  level:
    jdbc:
      audit: error
      resultset: error
      sqlonly: error
      
env:
  home:
    path: /home/admin/release/     
