spring:
  profiles.active: dev
  aop:
    proxy-target-class: true
  application:
    name: imbird-vote
    

logging:
  level:
    jdbc:
      audit: error
      resultset: error
      sqlonly: error

