server:
  port: 8810
  context-path: /
spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://118.31.47.102:3306/vote?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    druid:
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=100
      maxActive: 300
      initialSize: 1
      maxWait: 10000
      minIdle: 100
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
    
      
env: 
  home: 
    path: /Users/hxp/release
